import './globals.css'
import type { Metadata } from 'next'
import { Hanken_Grotesk } from 'next/font/google'

const monoton = Hanken_Grotesk({ weight: ["500", "700", "800"] ,subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={monoton.className + "font-medium text-lg"}>{children}</body>
    </html>
  )
}
